from sqlalchemy import select, desc
from sqlalchemy.ext.asyncio import AsyncSession

from database.checkpointer import delete_thread_checkpoints
from database.models import Agent, Thread
from schemas.thread import ThreadCreate


class ThreadService:

    async def create(self, session: AsyncSession, user_id: str, data: ThreadCreate) -> Thread:
        """Create a new thread, validating that the target agent belongs to the user.

        Title is intentionally omitted — it is auto-generated by the AI after the
        first completed message exchange.

        Args:
            session: Active async database session.
            user_id: The authenticated user's ID.
            data: Thread creation payload containing agent_id.

        Returns:
            The newly created Thread ORM instance.

        Raises:
            ValueError: If the agent does not exist or does not belong to the user.
        """
        agent_result = await session.execute(
            select(Agent).where(
                Agent.id == data.agent_id,
                Agent.user_id == user_id,
                Agent.is_active == True,
                Agent.parent_id == None,
            )
        )
        if not agent_result.scalar_one_or_none():
            raise ValueError("Agent not found or is a sub-agent")

        thread = Thread(
            user_id=user_id,
            agent_id=data.agent_id,
        )
        session.add(thread)
        await session.commit()
        await session.refresh(thread)
        return thread

    async def get_by_agent(
        self, session: AsyncSession, agent_id: str, user_id: str
    ) -> list[Thread]:
        """Return all active threads for a given agent, scoped to the requesting user.

        Args:
            session: Active async database session.
            agent_id: The agent's string ID.
            user_id: The authenticated user's ID.

        Returns:
            List of active Thread ORM instances.
        """
        result = await session.execute(
            select(Thread).where(
                Thread.agent_id == agent_id,
                Thread.user_id == user_id,
                Thread.is_active == True,
            )
            .order_by(desc(Thread.created_at))
        )
        return list(result.scalars().all())

    async def get_by_id(
        self, session: AsyncSession, thread_id: str, user_id: str
    ) -> Thread:
        """Fetch a single thread by ID, scoped to the requesting user.

        Args:
            session: Active async database session.
            thread_id: The thread's string ID.
            user_id: The authenticated user's ID.

        Returns:
            The Thread ORM instance.

        Raises:
            ValueError: If the thread does not exist or does not belong to the user.
        """
        result = await session.execute(
            select(Thread).where(
                Thread.id == thread_id,
                Thread.user_id == user_id,
                Thread.is_active == True,
            )
        )
        thread = result.scalar_one_or_none()
        if not thread:
            raise ValueError("Thread not found")
        return thread

    async def update_title(
        self, session: AsyncSession, thread_id: str, user_id: str, title: str
    ) -> Thread:
        """Update the title of an existing thread.

        Args:
            session: Active async database session.
            thread_id: The thread's string ID.
            user_id: The authenticated user's ID.
            title: New title string (already validated by the schema).

        Returns:
            The updated Thread ORM instance.

        Raises:
            ValueError: If the thread does not exist or does not belong to the user.
        """
        thread = await self.get_by_id(session, thread_id, user_id)
        thread.title = title
        await session.commit()
        await session.refresh(thread)
        return thread

    async def delete(self, session: AsyncSession, thread_id: str, user_id: str) -> str:
        """Soft-delete a thread and clean up its LangGraph checkpoint state.

        Sets is_active=False on the thread record (consistent with the rest of the
        soft-delete pattern) and removes associated checkpointer data so that
        conversation memory for this thread is freed.

        Args:
            session: Active async database session.
            thread_id: The thread's string ID.
            user_id: The authenticated user's ID.

        Raises:
            ValueError: If the thread does not exist or does not belong to the user.
        """
        thread = await self.get_by_id(session, thread_id, user_id)

        thread_name = thread.title

        thread.is_active = False
        await session.commit()

        await delete_thread_checkpoints(thread_id)

        return thread_name
